var jsonTexto = [
  [
    {"Capital":"leticia","leticia":"0","medellin":"0","arauca":"0","barranquilla":"0","Cartagena de Indias":"0","tunja":"0","manizales":"0","florencia":"0","yopal":"0","popayan":"0","valledupar":"0","quibdo":"0","monteria":"0","bogota":"0","inirida":"0","san_jose_del_guaviare":"0","neiva":"0","riohacha":"0","santa_marta":"0","villavicencio":"0","pasto":"0","san_jose_de_cucuta":"0","mocoa":"0","armenia":"0","pereira":"0","san_andres":"0","bucaramanga":"0","sincelejo":"0","ibague":"0","cali":"0","mitu":"0","puerto_carre�o":"0"}
    ,
    {"Capital":"medellin","leticia":"0","medellin":"0","arauca":"0","barranquilla":"0","Cartagena de Indias":"0","tunja":"1","manizales":"1","florencia":"0","yopal":"0","popayan":"0","valledupar":"0","quibdo":"1","monteria":"1","bogota":"0","inirida":"0","san_jose_del_guaviare":"0","neiva":"0","riohacha":"0","santa_marta":"0","villavicencio":"0","pasto":"0","san_jose_de_cucuta":"0","mocoa":"0","armenia":"0","pereira":"0","san_andres":"0","bucaramanga":"0","sincelejo":"0","ibague":"0","cali":"0","mitu":"0","puerto_carre�o":"0"}
    ,
    {"Capital":"arauca","leticia":"0","medellin":"0","arauca":"0","barranquilla":"0","Cartagena de Indias":"0","tunja":"0","manizales":"0","florencia":"0","yopal":"1","popayan":"0","valledupar":"0","quibdo":"0","monteria":"0","bogota":"0","inirida":"0","san_jose_del_guaviare":"0","neiva":"0","riohacha":"0","santa_marta":"0","villavicencio":"0","pasto":"0","san_jose_de_cucuta":"0","mocoa":"0","armenia":"0","pereira":"0","san_andres":"0","bucaramanga":"1","sincelejo":"0","ibague":"0","cali":"0","mitu":"0","puerto_carre�o":"0"}
    ,
    {"Capital":"barranquilla","leticia":"0","medellin":"0","arauca":"0","barranquilla":"0","Cartagena de Indias":"1","tunja":"0","manizales":"0","florencia":"0","yopal":"0","popayan":"0","valledupar":"1","quibdo":"0","monteria":"0","bogota":"0","inirida":"0","san_jose_del_guaviare":"0","neiva":"0","riohacha":"0","santa_marta":"0","villavicencio":"0","pasto":"0","san_jose_de_cucuta":"0","mocoa":"0","armenia":"0","pereira":"0","san_andres":"0","bucaramanga":"0","sincelejo":"0","ibague":"0","cali":"0","mitu":"0","puerto_carre�o":"0"}
    ,
    {"Capital":"cartagena_de_indias","leticia":"0","medellin":"0","arauca":"0","barranquilla":"1","Cartagena de Indias":"0","tunja":"0","manizales":"0","florencia":"0","yopal":"0","popayan":"0","valledupar":"0","quibdo":"0","monteria":"0","bogota":"0","inirida":"0","san_jose_del_guaviare":"0","neiva":"0","riohacha":"0","santa_marta":"0","villavicencio":"0","pasto":"0","san_jose_de_cucuta":"0","mocoa":"0","armenia":"0","pereira":"0","san_andres":"0","bucaramanga":"1","sincelejo":"1","ibague":"0","cali":"0","mitu":"0","puerto_carre�o":"0"}
    ,
    {"Capital":"tunja","leticia":"0","medellin":"1","arauca":"0","barranquilla":"0","Cartagena de Indias":"0","tunja":"0","manizales":"0","florencia":"0","yopal":"1","popayan":"0","valledupar":"0","quibdo":"0","monteria":"0","bogota":"1","inirida":"0","san_jose_del_guaviare":"0","neiva":"0","riohacha":"0","santa_marta":"0","villavicencio":"0","pasto":"0","san_jose_de_cucuta":"0","mocoa":"0","armenia":"0","pereira":"0","san_andres":"0","bucaramanga":"1","sincelejo":"0","ibague":"0","cali":"0","mitu":"0","puerto_carre�o":"0"}
    ,
    {"Capital":"manizales","leticia":"0","medellin":"1","arauca":"0","barranquilla":"0","Cartagena de Indias":"0","tunja":"0","manizales":"0","florencia":"0","yopal":"0","popayan":"0","valledupar":"0","quibdo":"0","monteria":"0","bogota":"1","inirida":"0","san_jose_del_guaviare":"0","neiva":"0","riohacha":"0","santa_marta":"0","villavicencio":"0","pasto":"0","san_jose_de_cucuta":"0","mocoa":"0","armenia":"0","pereira":"1","san_andres":"0","bucaramanga":"0","sincelejo":"0","ibague":"1","cali":"0","mitu":"0","puerto_carre�o":"0"}
    ,
    {"Capital":"florencia","leticia":"0","medellin":"0","arauca":"0","barranquilla":"0","Cartagena de Indias":"0","tunja":"0","manizales":"0","florencia":"0","yopal":"0","popayan":"1","valledupar":"0","quibdo":"0","monteria":"0","bogota":"0","inirida":"0","san_jose_del_guaviare":"0","neiva":"0","riohacha":"0","santa_marta":"0","villavicencio":"0","pasto":"0","san_jose_de_cucuta":"0","mocoa":"1","armenia":"0","pereira":"0","san_andres":"0","bucaramanga":"0","sincelejo":"0","ibague":"0","cali":"0","mitu":"0","puerto_carre�o":"0"}
    ,
    {"Capital":"yopal","leticia":"0","medellin":"0","arauca":"1","barranquilla":"0","Cartagena de Indias":"0","tunja":"1","manizales":"0","florencia":"0","yopal":"0","popayan":"0","valledupar":"0","quibdo":"0","monteria":"0","bogota":"0","inirida":"0","san_jose_del_guaviare":"0","neiva":"0","riohacha":"0","santa_marta":"0","villavicencio":"0","pasto":"0","san_jose_de_cucuta":"0","mocoa":"0","armenia":"0","pereira":"0","san_andres":"0","bucaramanga":"0","sincelejo":"0","ibague":"0","cali":"0","mitu":"0","puerto_carre�o":"1"}
    ,
    {"Capital":"popayan","leticia":"0","medellin":"0","arauca":"0","barranquilla":"0","Cartagena de Indias":"0","tunja":"0","manizales":"0","florencia":"1","yopal":"0","popayan":"0","valledupar":"0","quibdo":"0","monteria":"0","bogota":"0","inirida":"0","san_jose_del_guaviare":"0","neiva":"1","riohacha":"0","santa_marta":"0","villavicencio":"0","pasto":"1","san_jose_de_cucuta":"0","mocoa":"0","armenia":"0","pereira":"0","san_andres":"0","bucaramanga":"0","sincelejo":"0","ibague":"0","cali":"1","mitu":"0","puerto_carre�o":"0"}
    ,
    {"Capital":"valledupar","leticia":"0","medellin":"0","arauca":"0","barranquilla":"1","Cartagena de Indias":"0","tunja":"0","manizales":"0","florencia":"0","yopal":"0","popayan":"0","valledupar":"0","quibdo":"0","monteria":"0","bogota":"0","inirida":"0","san_jose_del_guaviare":"0","neiva":"0","riohacha":"1","santa_marta":"1","villavicencio":"0","pasto":"0","san_jose_de_cucuta":"1","mocoa":"0","armenia":"0","pereira":"0","san_andres":"0","bucaramanga":"0","sincelejo":"0","ibague":"0","cali":"0","mitu":"0","puerto_carre�o":"0"}
    ,
    {"Capital":"quibdo","leticia":"0","medellin":"1","arauca":"0","barranquilla":"0","Cartagena de Indias":"0","tunja":"0","manizales":"0","florencia":"0","yopal":"0","popayan":"0","valledupar":"0","quibdo":"0","monteria":"0","bogota":"0","inirida":"0","san_jose_del_guaviare":"0","neiva":"0","riohacha":"0","santa_marta":"0","villavicencio":"0","pasto":"0","san_jose_de_cucuta":"0","mocoa":"0","armenia":"0","pereira":"0","san_andres":"0","bucaramanga":"0","sincelejo":"0","ibague":"0","cali":"0","mitu":"0","puerto_carre�o":"0"}
    ,
    {"Capital":"monteria","leticia":"0","medellin":"1","arauca":"0","barranquilla":"0","Cartagena de Indias":"0","tunja":"0","manizales":"0","florencia":"0","yopal":"0","popayan":"0","valledupar":"0","quibdo":"0","monteria":"0","bogota":"0","inirida":"0","san_jose_del_guaviare":"0","neiva":"0","riohacha":"0","santa_marta":"0","villavicencio":"0","pasto":"0","san_jose_de_cucuta":"0","mocoa":"0","armenia":"0","pereira":"0","san_andres":"0","bucaramanga":"0","sincelejo":"1","ibague":"0","cali":"0","mitu":"0","puerto_carre�o":"0"}
    ,
    {"Capital":"bogota","leticia":"0","medellin":"0","arauca":"0","barranquilla":"0","Cartagena de Indias":"0","tunja":"1","manizales":"1","florencia":"0","yopal":"0","popayan":"0","valledupar":"0","quibdo":"0","monteria":"0","bogota":"0","inirida":"0","san_jose_del_guaviare":"0","neiva":"0","riohacha":"0","santa_marta":"0","villavicencio":"1","pasto":"0","san_jose_de_cucuta":"0","mocoa":"0","armenia":"0","pereira":"0","san_andres":"0","bucaramanga":"0","sincelejo":"0","ibague":"1","cali":"0","mitu":"0","puerto_carre�o":"0"}
    ,
    {"Capital":"inirida","leticia":"0","medellin":"0","arauca":"0","barranquilla":"0","Cartagena de Indias":"0","tunja":"0","manizales":"0","florencia":"0","yopal":"0","popayan":"0","valledupar":"0","quibdo":"0","monteria":"0","bogota":"0","inirida":"0","san_jose_del_guaviare":"0","neiva":"0","riohacha":"0","santa_marta":"0","villavicencio":"0","pasto":"0","san_jose_de_cucuta":"0","mocoa":"0","armenia":"0","pereira":"0","san_andres":"0","bucaramanga":"0","sincelejo":"0","ibague":"0","cali":"0","mitu":"0","puerto_carre�o":"1"}
    ,
    {"Capital":"san_jose_del_guaviare","leticia":"0","medellin":"0","arauca":"0","barranquilla":"0","Cartagena de Indias":"0","tunja":"0","manizales":"0","florencia":"0","yopal":"0","popayan":"0","valledupar":"0","quibdo":"0","monteria":"0","bogota":"0","inirida":"0","san_jose_del_guaviare":"0","neiva":"0","riohacha":"0","santa_marta":"0","villavicencio":"1","pasto":"0","san_jose_de_cucuta":"0","mocoa":"0","armenia":"0","pereira":"0","san_andres":"0","bucaramanga":"0","sincelejo":"0","ibague":"0","cali":"0","mitu":"0","puerto_carre�o":"0"}
    ,
    {"Capital":"neiva","leticia":"0","medellin":"0","arauca":"0","barranquilla":"0","Cartagena de Indias":"0","tunja":"0","manizales":"0","florencia":"0","yopal":"0","popayan":"1","valledupar":"0","quibdo":"0","monteria":"0","bogota":"0","inirida":"0","san_jose_del_guaviare":"0","neiva":"0","riohacha":"0","santa_marta":"0","villavicencio":"0","pasto":"0","san_jose_de_cucuta":"0","mocoa":"0","armenia":"0","pereira":"0","san_andres":"0","bucaramanga":"0","sincelejo":"0","ibague":"1","cali":"0","mitu":"0","puerto_carre�o":"0"}
    ,
    {"Capital":"riohacha","leticia":"0","medellin":"0","arauca":"0","barranquilla":"0","Cartagena de Indias":"0","tunja":"0","manizales":"0","florencia":"0","yopal":"0","popayan":"0","valledupar":"1","quibdo":"0","monteria":"0","bogota":"0","inirida":"0","san_jose_del_guaviare":"0","neiva":"0","riohacha":"0","santa_marta":"0","villavicencio":"0","pasto":"0","san_jose_de_cucuta":"0","mocoa":"0","armenia":"0","pereira":"0","san_andres":"0","bucaramanga":"0","sincelejo":"0","ibague":"0","cali":"0","mitu":"0","puerto_carre�o":"0"}
    ,
    {"Capital":"santa_marta","leticia":"0","medellin":"0","arauca":"0","barranquilla":"0","Cartagena de Indias":"0","tunja":"0","manizales":"0","florencia":"0","yopal":"0","popayan":"0","valledupar":"1","quibdo":"0","monteria":"0","bogota":"0","inirida":"0","san_jose_del_guaviare":"0","neiva":"0","riohacha":"0","santa_marta":"0","villavicencio":"0","pasto":"0","san_jose_de_cucuta":"0","mocoa":"0","armenia":"0","pereira":"0","san_andres":"0","bucaramanga":"0","sincelejo":"0","ibague":"0","cali":"0","mitu":"0","puerto_carre�o":"0"}
    ,
    {"Capital":"villavicencio","leticia":"0","medellin":"0","arauca":"0","barranquilla":"0","Cartagena de Indias":"0","tunja":"0","manizales":"0","florencia":"0","yopal":"0","popayan":"0","valledupar":"0","quibdo":"0","monteria":"0","bogota":"1","inirida":"0","san_jose_del_guaviare":"1","neiva":"0","riohacha":"0","santa_marta":"0","villavicencio":"0","pasto":"0","san_jose_de_cucuta":"0","mocoa":"0","armenia":"0","pereira":"0","san_andres":"0","bucaramanga":"0","sincelejo":"0","ibague":"0","cali":"0","mitu":"0","puerto_carre�o":"0"}
    ,
    {"Capital":"pasto","leticia":"0","medellin":"0","arauca":"0","barranquilla":"0","Cartagena de Indias":"0","tunja":"0","manizales":"0","florencia":"0","yopal":"0","popayan":"1","valledupar":"0","quibdo":"0","monteria":"0","bogota":"0","inirida":"0","san_jose_del_guaviare":"0","neiva":"0","riohacha":"0","santa_marta":"0","villavicencio":"0","pasto":"0","san_jose_de_cucuta":"0","mocoa":"1","armenia":"0","pereira":"0","san_andres":"0","bucaramanga":"0","sincelejo":"0","ibague":"0","cali":"0","mitu":"0","puerto_carre�o":"0"}
    ,
    {"Capital":"san_jose_de_cucuta","leticia":"0","medellin":"0","arauca":"0","barranquilla":"0","Cartagena de Indias":"0","tunja":"0","manizales":"0","florencia":"0","yopal":"0","popayan":"0","valledupar":"1","quibdo":"0","monteria":"0","bogota":"0","inirida":"0","san_jose_del_guaviare":"0","neiva":"0","riohacha":"0","santa_marta":"0","villavicencio":"0","pasto":"0","san_jose_de_cucuta":"0","mocoa":"0","armenia":"0","pereira":"0","san_andres":"0","bucaramanga":"1","sincelejo":"0","ibague":"0","cali":"0","mitu":"0","puerto_carre�o":"0"}
    ,
    {"Capital":"mocoa","leticia":"0","medellin":"0","arauca":"0","barranquilla":"0","Cartagena de Indias":"0","tunja":"0","manizales":"0","florencia":"1","yopal":"0","popayan":"0","valledupar":"0","quibdo":"0","monteria":"0","bogota":"0","inirida":"0","san_jose_del_guaviare":"0","neiva":"0","riohacha":"0","santa_marta":"0","villavicencio":"0","pasto":"1","san_jose_de_cucuta":"0","mocoa":"0","armenia":"0","pereira":"0","san_andres":"0","bucaramanga":"0","sincelejo":"0","ibague":"0","cali":"0","mitu":"0","puerto_carre�o":"0"}
    ,
    {"Capital":"armenia","leticia":"0","medellin":"0","arauca":"0","barranquilla":"0","Cartagena de Indias":"0","tunja":"0","manizales":"0","florencia":"0","yopal":"0","popayan":"0","valledupar":"0","quibdo":"0","monteria":"0","bogota":"0","inirida":"0","san_jose_del_guaviare":"0","neiva":"0","riohacha":"0","santa_marta":"0","villavicencio":"0","pasto":"0","san_jose_de_cucuta":"0","mocoa":"0","armenia":"0","pereira":"1","san_andres":"0","bucaramanga":"0","sincelejo":"0","ibague":"1","cali":"1","mitu":"0","puerto_carre�o":"0"}
    ,
    {"Capital":"pereira","leticia":"0","medellin":"0","arauca":"0","barranquilla":"0","Cartagena de Indias":"0","tunja":"0","manizales":"1","florencia":"0","yopal":"0","popayan":"0","valledupar":"0","quibdo":"0","monteria":"0","bogota":"0","inirida":"0","san_jose_del_guaviare":"0","neiva":"0","riohacha":"0","santa_marta":"0","villavicencio":"0","pasto":"0","san_jose_de_cucuta":"0","mocoa":"0","armenia":"1","pereira":"0","san_andres":"0","bucaramanga":"0","sincelejo":"0","ibague":"0","cali":"0","mitu":"0","puerto_carre�o":"0"}
    ,
    {"Capital":"san_andres","leticia":"0","medellin":"0","arauca":"0","barranquilla":"0","Cartagena de Indias":"0","tunja":"0","manizales":"0","florencia":"0","yopal":"0","popayan":"0","valledupar":"0","quibdo":"0","monteria":"0","bogota":"0","inirida":"0","san_jose_del_guaviare":"0","neiva":"0","riohacha":"0","santa_marta":"0","villavicencio":"0","pasto":"0","san_jose_de_cucuta":"0","mocoa":"0","armenia":"0","pereira":"0","san_andres":"0","bucaramanga":"0","sincelejo":"0","ibague":"0","cali":"0","mitu":"0","puerto_carre�o":"0"}
    ,
    {"Capital":"bucaramanga","leticia":"0","medellin":"0","arauca":"1","barranquilla":"0","Cartagena de Indias":"1","tunja":"1","manizales":"0","florencia":"0","yopal":"0","popayan":"0","valledupar":"0","quibdo":"0","monteria":"0","bogota":"0","inirida":"0","san_jose_del_guaviare":"0","neiva":"0","riohacha":"0","santa_marta":"0","villavicencio":"0","pasto":"0","san_jose_de_cucuta":"1","mocoa":"0","armenia":"0","pereira":"0","san_andres":"0","bucaramanga":"0","sincelejo":"1","ibague":"0","cali":"0","mitu":"0","puerto_carre�o":"0"}
    ,
    {"Capital":"sincelejo","leticia":"0","medellin":"0","arauca":"0","barranquilla":"0","Cartagena de Indias":"1","tunja":"0","manizales":"0","florencia":"0","yopal":"0","popayan":"0","valledupar":"0","quibdo":"0","monteria":"1","bogota":"0","inirida":"0","san_jose_del_guaviare":"0","neiva":"0","riohacha":"0","santa_marta":"0","villavicencio":"0","pasto":"0","san_jose_de_cucuta":"0","mocoa":"0","armenia":"0","pereira":"0","san_andres":"0","bucaramanga":"1","sincelejo":"0","ibague":"0","cali":"0","mitu":"0","puerto_carre�o":"0"}
    ,
    {"Capital":"ibague","leticia":"0","medellin":"0","arauca":"0","barranquilla":"0","Cartagena de Indias":"0","tunja":"0","manizales":"1","florencia":"0","yopal":"0","popayan":"0","valledupar":"0","quibdo":"0","monteria":"0","bogota":"1","inirida":"0","san_jose_del_guaviare":"0","neiva":"1","riohacha":"0","santa_marta":"0","villavicencio":"0","pasto":"0","san_jose_de_cucuta":"0","mocoa":"0","armenia":"1","pereira":"0","san_andres":"0","bucaramanga":"0","sincelejo":"0","ibague":"0","cali":"0","mitu":"0","puerto_carre�o":"0"}
    ,
    {"Capital":"cali","leticia":"0","medellin":"0","arauca":"0","barranquilla":"0","Cartagena de Indias":"0","tunja":"0","manizales":"0","florencia":"0","yopal":"0","popayan":"1","valledupar":"0","quibdo":"0","monteria":"0","bogota":"0","inirida":"0","san_jose_del_guaviare":"0","neiva":"0","riohacha":"0","santa_marta":"0","villavicencio":"0","pasto":"0","san_jose_de_cucuta":"0","mocoa":"0","armenia":"1","pereira":"0","san_andres":"0","bucaramanga":"0","sincelejo":"0","ibague":"0","cali":"0","mitu":"0","puerto_carre�o":"0"}
    ,
    {"Capital":"mitu","leticia":"0","medellin":"0","arauca":"0","barranquilla":"0","Cartagena de Indias":"0","tunja":"0","manizales":"0","florencia":"0","yopal":"0","popayan":"0","valledupar":"0","quibdo":"0","monteria":"0","bogota":"0","inirida":"0","san_jose_del_guaviare":"0","neiva":"0","riohacha":"0","santa_marta":"0","villavicencio":"0","pasto":"0","san_jose_de_cucuta":"0","mocoa":"0","armenia":"0","pereira":"0","san_andres":"0","bucaramanga":"0","sincelejo":"0","ibague":"0","cali":"0","mitu":"0","puerto_carre�o":"0"}
    ,
    {"Capital":"puerto_carreno","leticia":"0","medellin":"0","arauca":"0","barranquilla":"0","Cartagena de Indias":"0","tunja":"0","manizales":"0","florencia":"0","yopal":"1","popayan":"0","valledupar":"0","quibdo":"0","monteria":"0","bogota":"0","inirida":"1","san_jose_del_guaviare":"0","neiva":"0","riohacha":"0","santa_marta":"0","villavicencio":"0","pasto":"0","san_jose_de_cucuta":"0","mocoa":"0","armenia":"0","pereira":"0","san_andres":"0","bucaramanga":"0","sincelejo":"0","ibague":"0","cali":"0","mitu":"0","puerto_carre�o":"0"}
    
  ]    
];
export let red = JSON.parse(JSON.stringify(jsonTexto));
console.log(red);
